"""empty message

Revision ID: eaadc4857cf7
Revises: 
Create Date: 2021-01-04 14:46:10.167532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaadc4857cf7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.Column('currency', sa.String(length=5), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('shop_order_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_amount'), 'payment', ['amount'], unique=False)
    op.create_index(op.f('ix_payment_currency'), 'payment', ['currency'], unique=False)
    op.create_index(op.f('ix_payment_timestamp'), 'payment', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_timestamp'), table_name='payment')
    op.drop_index(op.f('ix_payment_currency'), table_name='payment')
    op.drop_index(op.f('ix_payment_amount'), table_name='payment')
    op.drop_table('payment')
    # ### end Alembic commands ###
